version : "3.6"

services :

  mariadb :
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb

